{
    "name": "Tennis sports center",
    "version": "1.0",
    "category": "Sport",
    "sequence": 10,
    "summary": "Sports Center",
    "description": """
                    Sports center with a management and control system for the process of booking and using sports courts
                    """,
    "depends": [],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sports_center_workout.xml",
        "data/sports_center_booking_time_interval.xml",
        "views/sports_center_view.xml",
        "views/sports_center_court_card_view.xml",
        "views/sports_center_court_view.xml",
        "wizard/edit_sports_court_data_view.xml",
        "views/sports_center_card_view.xml",
        "wizard/edit_center_card_view.xml",
        "views/sports_center_employee_view.xml",
        "views/sports_center_financial_report_view.xml",
        "views/sports_center_accrual_employee_view.xml",
        "views/sports_center_employee_salary.xml",
        "views/sports_center_court_booking_view.xml",
        "views/sports_center_court_booking_time_view.xml",
        "views/sports_center_user_view.xml",
        "views/sports_center_post_view.xml",
        "views/sports_center_workout_view.xml",
        "views/sports_center_menu.xml",
    ],
    "license": "LGPL-3",
}
